[slackana-11] - [Markup] Create Settings Modal in Profile Avatar Dropdown
abduljalilpalala/ps-slackana pull request #12
Opened 2022-09-28 07:44 UTC by pong-sun

## Issue Link
-  https://app.asana.com/0/1203010757822877/1203026696022137/f

## Definition of Done
- [x] User can open settings modal
- [x] User can select in the settings menu Profile, Security, Notification
- [x] User can toggle the toggle switch button in notification

## Notes 
- (Optional)

## Pre-condition
- yarn

## Expected Output
- The settings modal should popup after the user clicked the profile button
- The settings modal should close if the user clicked the close button and clicked outside the modal

## Screenshots/Recordings
- Profile
![image](https://user-images.githubusercontent.com/104751512/192718733-9e00b1eb-91c2-48c0-b4d4-110df8231bee.png)

- Security
![image](https://user-images.githubusercontent.com/104751512/192718814-f56dc43b-c585-4fc3-bfda-4e9ce4877f92.png)
 
- Notification
![image](https://user-images.githubusercontent.com/104751512/192718847-16f20599-8e6b-48f9-88e9-d7c34a987f62.png)

2022-09-28 07:50 UTC, abduljalilpalala commented on client/src/components/templates/DialogBox/index.tsx
> +export default DialogBox;
Add new line

2022-09-28 07:55 UTC, abduljalilpalala requested changes

2022-09-28 07:55 UTC, abduljalilpalala commented on client/src/shared/interfaces/index.ts
> +>>>>>>> develop
Remove `<<<<<<< HEAD` and `>>>>>>> develop`

2022-09-28 07:55 UTC, abduljalilpalala commented on client/src/shared/twin/home-content.style.ts
> +}
Add new line

2022-09-28 07:55 UTC, abduljalilpalala commented on client/src/shared/twin/settings-modal.style.ts
> +}
Add new line

2022-09-28 09:17 UTC, jsvelte reviewed
Approved 💯

2022-09-28 10:02 UTC, abduljalilpalala approved these changes

2022-09-28 10:02 UTC, merged

2022-09-30 14:56 UTC, ipilikent reviewed
## Approved PR
-  All displayed is the same as the Figma design
-  The Setting Modal is responsive
-  Toggle the toggle switch button is function

## Proof
<details>

![Setting Modal](https://user-images.githubusercontent.com/110364019/193292109-fd9e77fc-6be1-455d-b4f4-3b1d060a8cdd.gif)


</details>

Test Case : https://docs.google.com/spreadsheets/d/1pa_tZVA7ar1JsgKeIS_0JTaJX9ZywKrX/edit#gid=1229389153
-----
- Total Test time: 1.6 hrs
- Total Comments: 0
- Total Iterations: 1