[slackana-44] - [Markup] Create Project Overview Page
abduljalilpalala/ps-slackana pull request #21
Opened 2022-09-30 09:39 UTC by pong-sun

## Issue Link
-  https://app.asana.com/0/1203011167276287/1203026696603983/f

## Definition of Done
- [x] User can add team
- [x] User cannot delete the team if it only has one left
- [x]  User can close the modal
- [x] User can open the modal when clicking the add team button

## Notes 
- (Optional)

## Pre-condition
- yarn

## Expected Output
- The add team modal should pop up when the user clicks the add team button
- The add team modal should close when the user clicks outside of the modal or clicks the close button
- It should disable the team when there's only one left
- It should add a team if the user inputs teams in input tags

## Screenshots/Recordings
- Add team modal
![image](https://user-images.githubusercontent.com/104751512/193241452-1e81e528-57c0-40fd-b13c-11725dd030d1.png)
- Disabled
![image](https://user-images.githubusercontent.com/104751512/193241950-2d5f7f85-8a6a-494e-9ea0-18a0ecfa9752.png)

2022-09-30 09:44 UTC, jsvelte approved these changes
# Approved 💯

2022-09-30 09:44 UTC, jsvelte commented on client/src/components/molecules/TeamTemplate/index.tsx
> +export default TeamTemplate;
Add new line

2022-09-30 09:54 UTC, abduljalilpalala commented on client/src/shared/jsons/membersData.ts
> +]
Add new line

2022-09-30 09:55 UTC, abduljalilpalala commented on client/src/shared/jsons/teamTempoData.ts
> +];
Add new line

2022-09-30 09:55 UTC, abduljalilpalala requested changes
Check comments.

2022-09-30 10:17 UTC, abduljalilpalala approved these changes
Check comments.

2022-09-30 10:18 UTC, merged

2022-10-03 04:03 UTC, ipilikent reviewed
## Approved PR
-  All displayed is the same as the Figma design
-  The modal is displayed
-  The Project Overview is responsive

## Proof
<details>

![Project Overview](https://user-images.githubusercontent.com/110364019/193499452-1d7d6728-28c5-48df-a4c7-e49766435259.gif)


</details>

Test Case : https://docs.google.com/spreadsheets/d/1pa_tZVA7ar1JsgKeIS_0JTaJX9ZywKrX/edit?pli=1#gid=421111680
-----
- Total Test time: 1.8 hrs
- Total Comments: 0
- Total Iterations: 0